"""initial schema

Revision ID: 63bbc337c17a
Revises: 
Create Date: 2026-03-03 15:29:10.026676
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '63bbc337c17a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('seed_urls', mysql.JSON(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('text_content', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('meta_description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('pending', 'indexing', 'indexed', 'failed', name='page_status'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_table('crawl_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('source_page_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'crawling', 'done', 'failed', 'skipped', name='crawl_status'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_table('image_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.String(length=1024), nullable=True),
    sa.Column('embedding', sa.LargeBinary(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_embeddings_page_id'), 'image_embeddings', ['page_id'], unique=False)
    op.create_table('text_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.SmallInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_embeddings_page_id'), 'text_embeddings', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_embeddings_page_id'), table_name='text_embeddings')
    op.drop_table('text_embeddings')
    op.drop_index(op.f('ix_image_embeddings_page_id'), table_name='image_embeddings')
    op.drop_table('image_embeddings')
    op.drop_table('crawl_queue')
    op.drop_table('pages')
    op.drop_table('crawl_state')
    # ### end Alembic commands ###
